export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  PACKED = 'PACKED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED'
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  ARCHIVED = 'ARCHIVED'
}

export enum StockMovementType {
  STOCK_IN = 'STOCK_IN',
  STOCK_OUT = 'STOCK_OUT',
  ADJUSTMENT = 'ADJUSTMENT',
  ADJUSTMENT_DAMAGE = 'ADJUSTMENT_DAMAGE',
  ADJUSTMENT_EXPIRED = 'ADJUSTMENT_EXPIRED',
  ADJUSTMENT_PHYSICAL_COUNT = 'ADJUSTMENT_PHYSICAL_COUNT',
  TRANSFER = 'TRANSFER',
  SCRAP = 'SCRAP',
  RETURN = 'RETURN'
}

export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  TRIAL = 'TRIAL',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
  PROVISIONING = 'PROVISIONING'
}

export enum SubscriptionTier {
  BASIC = 'BASIC',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL'
}
